### ISSUE TITLE
不清楚该如何操作

### ISSUE THREAD

**Issue by Harmskyblue** [JMBQ/azurlane#2]
请问能发布一个修改好的apk吗

**Comment by JMBQ** [comment]
可以的，我只提供了so，修改是你们做的，发布权归你们，只要不贩卖都行

**Comment by Harmskyblue** [comment]
我用apktool反编译安装包后，在onCreate的.local 2下面复制了这个语句然后保存
![Snipaste_2024-11-23_14-23-40](https://github.com/user-attachments/assets/7dd71aef-c970-4794-9fd0-97da5010e8b0)
再把release里的so复制到对应的lib里的三个文件夹
![image](https://github.com/user-attachments/assets/c7e4de58-ecb5-4480-adb8-9c4258ce5e0c)
![image](https://github.com/user-attachments/assets/d0128616-3d03-4a81-8e0d-7a30202ced84)
![image](https://github.com/user-attachments/assets/71233da0-24f4-4494-aea5-fbf721abf766)
最后用apktool编译保存，签名，安装到模拟器里运行时还是闪退且显示修改之前的提示
![image](https://github.com/user-attachments/assets/065336f7-9599-4bc7-90b3-f32e51548598)
不知道哪步做错了

**Comment by JMBQ** [comment]
为什么要加载英仙座？！同时加载会闪退就是它引起的

**Comment by Harmskyblue** [comment]
> 为什么要加载英仙座？！同时加载会闪退就是它引起的
所以要删除下面那两行persus吗

**Comment by JMBQ** [comment]
你添加的英仙座的3行代码全删掉就正常了

**Comment by Harmskyblue** [comment]
> 你添加的英仙座的3行代码全删掉就正常了

我是在英仙座的包上修改的，原来在官方的包上修改就行了，感谢，已成功
